repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: master # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: shellcheck
      - id: terragrunt-hclfmt
